### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by soyuka** [api-platform/doc#66] opened 2016-06-20 08:57 UTC
Could the repository be renamed to `api-platform-docs`, like symfony does it? 

It's better when forking, `doc` is too common.

**Comment by teohhanhui** [comment] 2016-06-20 09:04
Duplicate of #39

**Closed by teohhanhui** 2016-06-20 09:04 UTC

**Comment by soyuka** [comment] 2016-06-20 09:05
Yes indeed, I thought I saw it somewhere, thx.
